[package]
name = "zhd"
version = "0.1.0"
edition = "2024"
[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 'z'
strip = true
panic = "abort"
ar = "llvm-ar"
linker = "aarch64-linux-android29-clang"
[dependencies]
